### ISSUE TITLE
dies on startup: Cannot call method 'apply' of undefined

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/hoodie-plugin-global-share#3]
```
~$ cd /tmp
/tmp$ hoodie new sharetest

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.4.6 (node v0.10.25, npm 1.3.14, platform: darwin)

[hoodie] Updated package.json
[hoodie] fetching npm dependencies:
[hoodie] removing .git folder
[hoodie] preparing sharetest...
[hoodie] created project at /private/tmp/sharetest/
[hoodie] Installed all dependencies
You can now start using your hoodie app

  cd sharetest
  hoodie start

/tmp$ cd sharetest/
/tmp/sharetest$ hoodie install global-share 

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.4.6 (node v0.10.25, npm 1.3.14, platform: darwin)

[hoodie] Installing plugin(s): global-share
[hoodie] Successfully installed global-share plugin
[hoodie] Successfully updated package.json
/tmp/sharetest$ npm start

> oawyuftnafwoytun@1.0.9 start /private/tmp/sharetest
> node node_modules/hoodie-server/bin/start

Initializing...
CouchDB started: http://127.0.0.1:6083
Waiting for CouchDB [---*--] SUCCESS 
prompt: Please set an admin password :  
WWW:    http://127.0.0.1:6081
Admin:  http://127.0.0.1:6082
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'
Starting Plugin: 'hoodie-plugin-global-share'
TypeError: Cannot call method 'apply' of undefined
    at /private/tmp/sharetest/node_modules/hoodie-plugin-global-share/node_modules/async/lib/async.js:597:23
    at /private/tmp/sharetest/node_modules/hoodie-plugin-global-share/node_modules/async/lib/async.js:551:21
    at /private/tmp/sharetest/node_modules/hoodie-plugin-global-share/node_modules/async/lib/async.js:227:13
    at iterate (/private/tmp/sharetest/node_modules/hoodie-plugin-global-share/node_modules/async/lib/async.js:134:13)
    at /private/tmp/sharetest/node_modules/hoodie-plugin-global-share/node_modules/async/lib/async.js:145:25
    at /private/tmp/sharetest/node_modules/hoodie-plugin-global-share/node_modules/async/lib/async.js:229:17
    at /private/tmp/sharetest/node_modules/hoodie-plugin-global-share/node_modules/async/lib/async.js:556:34
    at /private/tmp/sharetest/node_modules/hoodie-server/node_modules/hoodie-plugins-manager/node_modules/hoodie-plugins-api/lib/databases.js:118:24
    at /private/tmp/sharetest/node_modules/hoodie-server/node_modules/hoodie-plugins-manager/node_modules/hoodie-plugins-api/node_modules/async/lib/async.js:226:13
    at /private/tmp/sharetest/node_modules/hoodie-server/node_modules/hoodie-plugins-manager/node_modules/hoodie-plugins-api/node_modules/async/lib/async.js:136:25

Stopping CouchDB...

npm ERR! oawyuftnafwoytun@1.0.9 start: `node node_modules/hoodie-server/bin/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oawyuftnafwoytun@1.0.9 start script.
npm ERR! This is most likely a problem with the oawyuftnafwoytun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/hoodie-server/bin/start
npm ERR! You can get their info via:
npm ERR!     npm owner ls oawyuftnafwoytun
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /private/tmp/sharetest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/tmp/sharetest/npm-debug.log
npm ERR! not ok code 0
```

**Comment by gr2m** [comment]
no clue why name got set to oawyuftnafwoytun, I've made an isssue on hoodie-cli:
https://github.com/hoodiehq/hoodie-cli/issues/96

**Comment by gr2m** [comment]
@caolan if you could look into this today, that'd be great. We want to use it for an app demonstration on Wednesday

**Comment by caolan** [comment]
OK I'll take a look

On 17 February 2014 09:56:29 GMT+00:00, Gregor Martynus notifications@github.com wrote:

> @caolan if you could look into this today, that'd be great. We want to
> use it for an app demonstration on Wednesday 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hoodiehq/hoodie-plugin-global-share/issues/3#issuecomment-35242654

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by janl** [comment]
should be fixed.
